apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 5m
  url: https://git.pmon.dev/schnappy/platform.git
  ref:
    branch: main
  secretRef:
    name: forgejo-credentials
