gitea:
  admin:
    existingSecret: forgejo-admin
  config:
    server:
      DOMAIN: git.pmon.dev
      ROOT_URL: "https://git.pmon.dev/"
      SSH_DOMAIN: git.pmon.dev
      DISABLE_SSH: true
      LFS_START_SERVER: true
    database:
      DB_TYPE: sqlite3
    service:
      DISABLE_REGISTRATION: false
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
    actions:
      ENABLED: false
    webhook:
      ALLOWED_HOST_LIST: "*"
    repository:
      DEFAULT_BRANCH: main
      DEFAULT_PRIVATE: true
    log:
      LEVEL: Warn
image:
  rootless: true
ingress:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi
persistence:
  enabled: true
  size: 20Gi
  storageClass: local-path
redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
