crds:
  enabled: true
maxConcurrentChallenges: 1
extraArgs:
  - --feature-gates=ExperimentalGatewayAPISupport=true
  - --dns01-recursive-nameservers=192.168.11.1:53
  - --dns01-recursive-nameservers-only
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
webhook:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
cainjector:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
