apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.7.1
      helm:
        valueFiles:
          - $values/clusters/production/envoy-gateway/values.yaml
    - repoURL: http://forgejo-http.forgejo.svc:3000/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: schnappy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
