apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: oci://code.forgejo.org/forgejo-helm
      chart: forgejo
      targetRevision: 16.2.0
      helm:
        valueFiles:
          - $values/clusters/production/forgejo/values.yaml
    - repoURL: https://git.pmon.dev/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
