apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: schnappy-apps-envs
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: production
            namespace: schnappy
            releaseName: schnappy
            valuesPath: clusters/production/schnappy/values.yaml
            syncWave: "2"
          - env: test
            namespace: schnappy-test
            releaseName: schnappy-test
            valuesPath: clusters/production/schnappy-test-apps/values.yaml
            syncWave: "2"
  template:
    metadata:
      name: "schnappy-{{env}}-apps"
      annotations:
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: http://192.168.11.5:3000/schnappy/platform.git
          targetRevision: main
          path: helm/schnappy
          helm:
            releaseName: "{{releaseName}}"
            valueFiles:
              - "$values/{{valuesPath}}"
        - repoURL: http://192.168.11.5:3000/schnappy/infra.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
