apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: schnappy-apps-envs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://192.168.11.5:3000/schnappy/infra.git
        revision: main
        directories:
          - path: "clusters/production/schnappy-*-apps"
  template:
    metadata:
      name: '{{ .path.basenameNormalized }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: http://192.168.11.5:3000/schnappy/platform.git
          targetRevision: main
          path: helm/schnappy
          helm:
            releaseName: '{{ index .path.segments 2 | trimSuffix "-apps" }}'
            valueFiles:
              - "$values/{{ .path.path }}/values.yaml"
        - repoURL: http://192.168.11.5:3000/schnappy/infra.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 | trimSuffix "-apps" }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: batch
          kind: Job
          jqPathExpressions:
            - .spec.selector
            - .spec.template.metadata.labels
