apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: schnappy-mesh-envs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://192.168.11.5:3000/schnappy/infra.git
        revision: main
        directories:
          - path: "clusters/production/schnappy-*-mesh"
  template:
    metadata:
      name: '{{ .path.basenameNormalized }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: http://192.168.11.5:3000/schnappy/platform.git
          targetRevision: main
          path: helm/schnappy-mesh
          helm:
            releaseName: '{{ index .path.segments 2 | trimSuffix "-mesh" }}'
            valueFiles:
              - "$values/{{ .path }}/values.yaml"
        - repoURL: http://192.168.11.5:3000/schnappy/infra.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 | trimSuffix "-mesh" }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - kind: Service
          name: schnappy-gateway-istio
          jqPathExpressions:
            - .spec
            - .metadata.labels
        - kind: ServiceAccount
          jqPathExpressions:
            - .metadata.labels
