apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: schnappy-data-envs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: http://192.168.11.5:3000/schnappy/infra.git
        revision: main
        directories:
          - path: "clusters/production/schnappy-*-data"
  template:
    metadata:
      name: '{{ .path.basenameNormalized }}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: http://192.168.11.5:3000/schnappy/platform.git
          targetRevision: main
          path: helm/schnappy-data
          helm:
            releaseName: '{{ index .path.segments 2 | trimSuffix "-data" }}'
            valueFiles:
              - "$values/{{ .path.path }}/values.yaml"
        - repoURL: http://192.168.11.5:3000/schnappy/infra.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index .path.segments 2 | trimSuffix "-data" }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
      ignoreDifferences:
        - group: scylla.scylladb.com
          kind: ScyllaCluster
          jqPathExpressions:
            - .spec.agentRepository
            - .spec.datacenter.racks[].storage
          managedFieldsManagers:
            - manager
        - group: postgresql.cnpg.io
          kind: Cluster
          jqPathExpressions:
            - .spec.affinity
            - .spec.enablePDB
            - .spec.failoverDelay
            - .spec.logLevel
            - .spec.maxSyncReplicas
            - .spec.minSyncReplicas
            - .spec.monitoring
            - .spec.postgresGID
            - .spec.postgresUID
            - .spec.primaryUpdateMethod
            - .spec.primaryUpdateStrategy
            - .spec.probes
            - .spec.replicationSlots
            - .spec.smartShutdownTimeout
            - .spec.startDelay
            - .spec.stopDelay
            - .spec.switchoverDelay
        - group: kafka.strimzi.io
          kind: KafkaTopic
          managedFieldsManagers:
            - strimzi-topic-operator
          jqPathExpressions:
            - .metadata
            - .spec
            - .status
        - group: kafka.strimzi.io
          kind: Kafka
          managedFieldsManagers:
            - strimzi-kafka-operator
        - group: kafka.strimzi.io
          kind: KafkaNodePool
          managedFieldsManagers:
            - strimzi-kafka-operator
        - group: batch
          kind: Job
          jqPathExpressions:
            - .spec.selector
            - .spec.template.metadata.labels
