apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schnappy-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: http://forgejo-http.forgejo.svc:3000/schnappy/platform.git
      path: helm/schnappy-mesh
      targetRevision: main
      helm:
        releaseName: schnappy
        valueFiles:
          - $values/clusters/production/schnappy-mesh/values.yaml
    - repoURL: http://forgejo-http.forgejo.svc:3000/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: schnappy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
    - group: gateway.networking.k8s.io
      kind: Gateway
      jsonPointers:
        - /metadata/annotations
        - /metadata/resourceVersion
