apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schnappy-auth
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: http://192.168.11.5:3000/schnappy/platform.git
      targetRevision: main
      path: helm/schnappy-auth
      helm:
        releaseName: schnappy
        valueFiles:
          - $values/clusters/production/schnappy-auth/values.yaml
    - repoURL: http://192.168.11.5:3000/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: schnappy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
