apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schnappy-observability
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://git.pmon.dev/schnappy/platform.git
      targetRevision: main
      path: helm/schnappy-observability
      helm:
        releaseName: schnappy
        valueFiles:
          - $values/clusters/production/schnappy-observability/values.yaml
    - repoURL: https://git.pmon.dev/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: schnappy-infra
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
