apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schnappy-data
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: http://192.168.11.5:3000/schnappy/platform.git
      targetRevision: main
      path: helm/schnappy-data
      helm:
        releaseName: schnappy
        valueFiles:
          - $values/clusters/production/schnappy-data/values.yaml
    - repoURL: http://192.168.11.5:3000/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: schnappy
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.persistentVolumeClaimRetentionPolicy
        - .spec.template.spec.containers[]?.terminationMessagePath
        - .spec.template.spec.containers[]?.terminationMessagePolicy
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
