apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: schnappy-test
  namespace: argocd
spec:
  project: default
  sources:
    - path: helm/schnappy-test
      repoURL: http://192.168.11.5:3000/schnappy/platform.git
      targetRevision: main
      helm:
        releaseName: schnappy
        valueFiles:
          - $values/clusters/production/schnappy-test/values.yaml
    - ref: values
      repoURL: http://192.168.11.5:3000/schnappy/infra.git
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: schnappy-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
