apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scylla-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://scylla-operator-charts.storage.googleapis.com/stable
      chart: scylla-operator
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $values/clusters/production/scylla-operator/values.yaml
    - repoURL: http://192.168.11.5:3000/schnappy/infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: scylla-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
