apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-registry-es
  namespace: schnappy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forgejo-registry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"git.pmon.dev":{"username":"{{ .registry_user }}","password":"{{ .registry_token }}"}}}
  data:
    - secretKey: registry_user
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_username
    - secretKey: registry_token
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-registry-es
  namespace: schnappy-test
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forgejo-registry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"git.pmon.dev":{"username":"{{ .registry_user }}","password":"{{ .registry_token }}"}}}
  data:
    - secretKey: registry_user
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_username
    - secretKey: registry_token
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-registry-es
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: forgejo-registry
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"git.pmon.dev":{"username":"{{ .registry_user }}","password":"{{ .registry_token }}"}}}
  data:
    - secretKey: registry_user
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_username
    - secretKey: registry_token
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_password
