apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: schnappy-default-deny
  namespace: schnappy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
