---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-backup-secret-es
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-backup-secret
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: secret/data/schnappy/velero
        property: minio_access_key
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: secret/data/schnappy/velero
        property: minio_secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials-es
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .minio_access_key }}
          aws_secret_access_key={{ .minio_secret_key }}
  data:
    - secretKey: minio_access_key
      remoteRef:
        key: secret/data/schnappy/velero
        property: minio_access_key
    - secretKey: minio_secret_key
      remoteRef:
        key: secret/data/schnappy/velero
        property: minio_secret_key
