apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-agent-secret
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: woodpecker-default-agent-secret
  data:
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: secret/data/schnappy/woodpecker
        property: agent-secret
