apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-ci-secrets-es
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: woodpecker-ci-secrets
  data:
    - secretKey: registry_user
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_username
    - secretKey: registry_token
      remoteRef:
        key: secret/data/schnappy/forgejo
        property: admin_password
    - secretKey: infra_repo_token
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: infra_repo_token
    - secretKey: nexus_npm_registry
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: nexus_npm_registry
    - secretKey: nexus_url
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: nexus_url
    - secretKey: nvd_api_key
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: nvd_api_key
    - secretKey: sonar_host_url
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: sonar_host_url
    - secretKey: sonar_token
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: sonar_token
    - secretKey: WOODPECKER_PROMETHEUS_AUTH_TOKEN
      remoteRef:
        key: secret/data/schnappy/woodpecker-ci
        property: prometheus_auth_token
