apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-forgejo-secret-es
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: woodpecker-forgejo-secret
  data:
    - secretKey: WOODPECKER_FORGEJO_CLIENT
      remoteRef:
        key: secret/data/schnappy/woodpecker-forgejo
        property: client_id
    - secretKey: WOODPECKER_FORGEJO_SECRET
      remoteRef:
        key: secret/data/schnappy/woodpecker-forgejo
        property: client_secret
