scyllaOperator:
  enabled: true

peerAuthentication:
  enabled: true
  mode: STRICT

authorizationPolicies:
  enabled: true

gateway:
  enabled: false
  external:
    enabled: true
    gatewayName: schnappy-gateway
    gatewayNamespace: schnappy
    hostname: test.pmon.dev

jwt:
  enabled: false
