resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

scylla:
  developerMode: true
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 5Gi
        storageClassName: local-path
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      # the operator's default for the agent is 50m (memory 10M, no limit); only the CPU is halved
      agentResources:
        requests:
          cpu: 25m
          memory: 10M
      placement: {}
