scyllaOperator:
  enabled: true

peerAuthentication:
  enabled: true
  mode: STRICT

authorizationPolicies:
  enabled: true

gateway:
  enabled: false
  external:
    enabled: true
    gatewayName: schnappy-infra-gateway
    gatewayNamespace: schnappy-infra
    sectionName: https-apex
    hostname: pmon.dev

jwt:
  enabled: false
