global:
  priorityClassName: system-cluster-critical

cni:
  enabled: true

meshConfig:
  accessLogFile: /dev/stdout
  enableTracing: true
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    tracing:
      zipkin:
        address: schnappy-tempo.schnappy-infra.svc:9411
      sampling: 1.0

pilot:
  env:
    ENABLE_NATIVE_SIDECARS: "false"
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
