profile: ambient

meshConfig:
  accessLogFile: /dev/stdout
  defaultConfig:
    holdApplicationUntilProxyStarts: false

pilot:
  env:
    ZTUNNEL_SA: istio-system/istio-ztunnel
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
