prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}
    ruleNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests: { cpu: 200m, memory: 512Mi }
      limits: { cpu: 4000m, memory: 4Gi }
    remoteWrite:
      - url: http://schnappy-mimir:9009/api/v1/push
    alertingEndpoints:
      - name: schnappy-alertmanager
        namespace: schnappy
        port: http
        scheme: http
    additionalScrapeConfigs:
      - job_name: schnappy-app
        metrics_path: /api/actuator/prometheus
        static_configs:
          - targets: ['schnappy-monitor:8080']
      - job_name: schnappy-kube-state-metrics
        static_configs:
          - targets: ['schnappy-kube-state-metrics:8080']

grafana:
  enabled: false
alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
coreDns:
  enabled: false
kubelet:
  enabled: false

prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
  podLabels:
    sidecar.istio.io/inject: "false"
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits: { cpu: 200m, memory: 256Mi }

defaultRules:
  create: false
